import Header from "@/app/ui/components/header/header"
import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import GlobalConfigs from '@/app/ui/components/globalConfigs/GlobalConfigs'

export const metadata: Metadata = {
    title: 'Home',
    description: 'Generated by create next app',
  }
  
  const locales = ['en', 'es'];
  
  export default function RootLayout({
    children, params
  }: {
    children: React.ReactNode,
    params: {
      locale : string
    }
  }) {
    if (!locales.includes(params.locale as any)) notFound();
    return (
        <>
          {children}
        </>
    )
  }